def a():
    print("Hello world")
    print("Hello world")
    print("Hello world")
    print("Hello world")
    print("Hello world")
    print("Hello world")
    print("Hello world")
    print("Hello world")
    print("Hello world")
    print("Hello world")  
a()
a()
a()